services:
  accounts:
    image: "scriptkddie404/account-service:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - software-alchemist

  loans:
    image: "scriptkddie404/loans-service:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - software-alchemist

  cards:
    image: "scriptkddie404/cards-service:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - software-alchemist

networks:
  software-alchemist:
    driver: "bridge"